service: login

frameworkVersion: ">=1.28.0 <2.0.0"

custom:
  config: ${file(../config.${self:provider.stage}.yml):config}

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  runtime: go1.x
  environment:
    DYNAMODB_USERS: ${self:custom.config.dynamodb_users}
    DYNAMODB_LOCATIONS: ${self:custom.config.dynamodb_locations}

    ##  iamRoleStatements:
#    - Effect: Allow
#      Action:
#        - dynamodb:Query
#      Resource:
#        - arn:aws:dynamodb:${self:provider.region}:${self:custom.config.account}:table/${self:custom.config.dynamodb_users}
#        - arn:aws:dynamodb:${self:provider.region}:${self:custom.config.account}:table/${self:custom.config.dynamodb_users}/index/*
#        - arn:aws:dynamodb:${self:provider.region}:${self:custom.config.account}:table/${self:custom.config.dynamodb_locations}
#        - arn:aws:dynamodb:${self:provider.region}:${self:custom.config.account}:table/${self:custom.config.dynamodb_locations}/index/*

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  v1:
    handler: bin/v1
    events:
      - http:
          path: login
          method: post
